### ISSUE TITLE
Tolerate node failures and balance external traffic load across multiple kube-proxy nodes

### ISSUE THREAD

**Issue by dshulyak** [Mirantis/k8s-externalipcontroller#10]
In current implementation we support only single replica managed by kubernetes deployment object.
Obviously it won't allow us to utilize multiple nodes with external connectivity.

To make it work we will change method of deployment to daemon sets, and also introduce multiple changes to support load balancing and tolerate network connectivity failures.

Issue will be updated with design proposal

**Comment by dshulyak** [comment]
Basic load balancing
---------------------------
We will use etcd to store list of assigned ip addresses. For instance:

`curl 'http://127.0.0.1:2379/v2/keys/externalip/10.108.0.3' -XPUT -d ttl=30 -d value=node1 prevExist=false`
```
{
  "action": "set",
  "node": {
    "key": "/externalip/10.108.0.3",
    "value": "node1",
    "expiration": "2016-10-21T13:05:20.842968859Z",
    "ttl": 30,
    "modifiedIndex": 956427,
    "createdIndex": 956427
  }
}
```

prevExist will ensure that only single node owns ip at any time. In this example after node1 acquired lease over 10.108.0.3 it will be responsible for renewing it.

Each ipcontroller  will watch externalip directory events.

`curl 'http://127.0.0.1:2379/v2/keys/members?wait=true&recursive=true'`

Using data from events each ipcontroller will make decision - to acquire ip or leave for another process. I realize that we may get some conflicts but they will be handled by cas (prevExist) shown earlier.

How we will handle node failures?
--------------------------------------------
Each ip will be created with ttl (lease if etcd v3). Once node will go offline (network partition, gcc stoptheworld or hardware problem) lease won't be renewed and all ipcontroller peers will receive expire event. On this event we will re-do assignment procedure (cas with prevExist) and send arping to update macaddress for ip which was reassigned.

Once original node is back we need to ensure that re-assigned ip was purged. For that we will simply compare list of assigned ips with etcd content.

@pigmej @adidenko please take a look, maybe you will have some questions
Alexey (for some reason can't reference you) ^

**Comment by pigmej** [comment]
@dshulyak 

Seems god to me, but
> For that we will simply compare list of assigned ips with etcd content.
This could be affected by race-conditions or just time issues. Because when the list is checked everything may be ok, but it will be the middle of assigning IP to different node. So this has to be checked more frequently than "once original node is back".

We have to be sure that we will not have "floating ip" problem.

**Comment by adidenko** [comment]
> prevExist will ensure that only single node owns ip at any time

We also need to support another case with ECMP load balancing when External IP is configured on EVERY node. Is it supported in the proposed scheme?

>  lease won't be renewed and all ipcontroller peers will receive expire event

TTL=30 is way too long for a fail-over. In case we set this value to something like 5, will it cause any performance related problems?

**Comment by dshulyak** [comment]
> We also need to support another case with ECMP load balancing when External IP is configured on EVERY node. Is it supported in the proposed scheme?

yes, we will have to deploy daemon set version with disabled ip load balancer (flag --ipmanagager)

> TTL=30 is way too long for a fail-over. In case we set this value to something like 5, will it cause any performance related problems?

Currently in master it is configured to be 4 seconds. It is just 1 request to etcd per ip each 4 seconds, i don't think it will be an issue, but i plan to run some perfomance measurements to be sure about it
