### ISSUE TITLE
Netmask is forced in claimscheduler

### ISSUE THREAD

**Issue by electrical** [Mirantis/k8s-externalipcontroller#102]
Currently the Netmask for an IP is set in the claimscheduler deployment.
Would it make sense to set it in the externalIp definition when assigning it to something in case there are different possible ip ranges?

**Comment by dshulyak** [comment]
@electrical Mask that is passed to scheduler should be ignored if you are using pool for auto-allocation https://github.com/Mirantis/k8s-externalipcontroller/blob/master/examples/ip-pool.yml

Unfortunately we can not specify mask as a part of externalIp, k8s validation will fail in this case.

**Comment by electrical** [comment]
Ahh okay. I see. thanks for the clarification!
