### ISSUE TITLE
Update to use CRD

### ISSUE THREAD

**Issue by dqminh** [Mirantis/k8s-externalipcontroller#133]
Just wonder if you have any plan to update the code to use CRD instead of TPR since TPR will be deprecated soon-ish.

More info: https://kubernetes.io/docs/tasks/access-kubernetes-api/migrate-third-party-resource/

**Comment by kwtalley** [comment]
Just updated to k8s 1.8 and believe I'm hitting this issue:

```error: unable to recognize "ip-pool.yml": no matches for ipcontroller.ext/, Kind=IpClaimPool```

any updates on migrating to CRD?

**Comment by mleklund** [comment]
I am also interested, but does not seem to work with k8s 1.8.

**Comment by dshulyak** [comment]
Hi folks
Looks like it shouldn't be hard to use TPR instead of CRD. Will try to do it this week
